/*
 * zigbee.h
 *
 *  Created on: 20 дек. 2016 г.
 *      Author: werwolf
 */

#ifndef ZIGBEE_H_
#define ZIGBEE_H_


#define ZIGBEE_FRAMECONTROL_FRAMETYPE0		0x0001		// bit0
#define ZIGBEE_FRAMECONTROL_FRAMETYPE1		0x0002		// bit1
#define ZIGBEE_FRAMECONTROL_FRAMETYPE2		0x0004		// bit2
#define ZIGBEE_FRAMECONTROL_SECURITYEN		0x0008		// bit3
#define ZIGBEE_FRAMECONTROL_FRAMEPEND		0x0010		// bit4
#define ZIGBEE_FRAMECONTROL_ACKREQUEST		0x0020		// bit5
#define ZIGBEE_FRAMECONTROL_INTRAPAN		0x0040		// bit6
#define ZIGBEE_FRAMECONTROL_RESERVED7		0x0080		// bit7
#define ZIGBEE_FRAMECONTROL_RESERVED8		0x0100		// bit8
#define ZIGBEE_FRAMECONTROL_RESERVED9		0x0200		// bit9
#define ZIGBEE_FRAMECONTROL_DESTADDRMODE0	0x0400		// bit10
#define ZIGBEE_FRAMECONTROL_DESTADDRMODE1	0x0800		// bit11
#define ZIGBEE_FRAMECONTROL_RESERVED12		0x1000		// bit12
#define ZIGBEE_FRAMECONTROL_RESERVED13		0x2000		// bit13
#define ZIGBEE_FRAMECONTROL_SRCADDRMODE0	0x4000		// bit14
#define ZIGBEE_FRAMECONTROL_SRCADDRMODE1	0x8000		// bit15

// Zigbee Frame types (3 bits)
#define ZIGBEE_FRAMECONTROL_FRAMETYPE_BEACON		0x00
#define ZIGBEE_FRAMECONTROL_FRAMETYPE_DATA			0x01
#define ZIGBEE_FRAMECONTROL_FRAMETYPE_ACK			0x02
#define ZIGBEE_FRAMECONTROL_FRAMETYPE_MACCOMM		0x03

// Zigbee Frame Destination address modes (2 bits)
// 1000 1000
#define ZIGBEE_FRAMECONTROL_DESTADDRMODE_NOPANNOADDR	(0x00 << 10)
#define ZIGBEE_FRAMECONTROL_DESTADDRMODE_SHORTADDR		(0x02 << 10)
#define ZIGBEE_FRAMECONTROL_DESTADDRMODE_LONGADDR		(0x03 << 10)

// Zigbee Frame Source address modes (2 bits)
#define ZIGBEE_FRAMECONTROL_SRCADDRMODE_NOPANNOADDR		(0x00 << 14)
#define ZIGBEE_FRAMECONTROL_SRCADDRMODE_SHORTADDR		(0x02 << 14)
#define ZIGBEE_FRAMECONTROL_SRCADDRMODE_LONGADDR		(0x03 << 14)

#endif /* ZIGBEE_H_ */
